/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as EspaceEntrepriseRouteImport } from './routes/espace-entreprise'
import { Route as EspaceUtilisateurRouteImport } from './routes/espace-utilisateur'
import { Route as PublierActualiteRouteImport } from './routes/publier-actualite'
import { Route as PublierOffreRouteImport } from './routes/publier-offre'
import { Route as SignalerRouteImport } from './routes/signaler'
import { Route as TableauStructureRouteImport } from './routes/tableau-structure'
import { Route as ActualitesIndexRouteImport } from './routes/actualites.index'
import { Route as ActualitesSlugRouteImport } from './routes/actualites.$slug'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSectionRouteImport } from './routes/admin.$section'
import { Route as EmploisIndexRouteImport } from './routes/emplois.index'
import { Route as EmploisIdRouteImport } from './routes/emplois.$id'
import { Route as EntreprisesIndexRouteImport } from './routes/entreprises.index'
import { Route as EntreprisesSlugRouteImport } from './routes/entreprises.$slug'
import { Route as InfosPratiquesIndexRouteImport } from './routes/infos-pratiques.index'
import { Route as InfosPratiquesSlugRouteImport } from './routes/infos-pratiques.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceEntrepriseRoute = EspaceEntrepriseRouteImport.update({
  id: '/espace-entreprise',
  path: '/espace-entreprise',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceUtilisateurRoute = EspaceUtilisateurRouteImport.update({
  id: '/espace-utilisateur',
  path: '/espace-utilisateur',
  getParentRoute: () => rootRouteImport,
} as any)
const PublierActualiteRoute = PublierActualiteRouteImport.update({
  id: '/publier-actualite',
  path: '/publier-actualite',
  getParentRoute: () => rootRouteImport,
} as any)
const PublierOffreRoute = PublierOffreRouteImport.update({
  id: '/publier-offre',
  path: '/publier-offre',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalerRoute = SignalerRouteImport.update({
  id: '/signaler',
  path: '/signaler',
  getParentRoute: () => rootRouteImport,
} as any)
const TableauStructureRoute = TableauStructureRouteImport.update({
  id: '/tableau-structure',
  path: '/tableau-structure',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesIndexRoute = ActualitesIndexRouteImport.update({
  id: '/actualites/',
  path: '/actualites/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesSlugRoute = ActualitesSlugRouteImport.update({
  id: '/actualites/$slug',
  path: '/actualites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectionRoute = AdminSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AdminRoute,
} as any)
const EmploisIndexRoute = EmploisIndexRouteImport.update({
  id: '/emplois/',
  path: '/emplois/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmploisIdRoute = EmploisIdRouteImport.update({
  id: '/emplois/$id',
  path: '/emplois/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EntreprisesIndexRoute = EntreprisesIndexRouteImport.update({
  id: '/entreprises/',
  path: '/entreprises/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntreprisesSlugRoute = EntreprisesSlugRouteImport.update({
  id: '/entreprises/$slug',
  path: '/entreprises/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InfosPratiquesIndexRoute = InfosPratiquesIndexRouteImport.update({
  id: '/infos-pratiques/',
  path: '/infos-pratiques/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfosPratiquesSlugRoute = InfosPratiquesSlugRouteImport.update({
  id: '/infos-pratiques/$slug',
  path: '/infos-pratiques/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/connexion': typeof ConnexionRoute
  '/espace-entreprise': typeof EspaceEntrepriseRoute
  '/espace-utilisateur': typeof EspaceUtilisateurRoute
  '/publier-actualite': typeof PublierActualiteRoute
  '/publier-offre': typeof PublierOffreRoute
  '/signaler': typeof SignalerRoute
  '/tableau-structure': typeof TableauStructureRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/admin/$section': typeof AdminSectionRoute
  '/emplois/$id': typeof EmploisIdRoute
  '/entreprises/$slug': typeof EntreprisesSlugRoute
  '/infos-pratiques/$slug': typeof InfosPratiquesSlugRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/emplois/': typeof EmploisIndexRoute
  '/entreprises/': typeof EntreprisesIndexRoute
  '/infos-pratiques/': typeof InfosPratiquesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/connexion': typeof ConnexionRoute
  '/espace-entreprise': typeof EspaceEntrepriseRoute
  '/espace-utilisateur': typeof EspaceUtilisateurRoute
  '/publier-actualite': typeof PublierActualiteRoute
  '/publier-offre': typeof PublierOffreRoute
  '/signaler': typeof SignalerRoute
  '/tableau-structure': typeof TableauStructureRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/admin/$section': typeof AdminSectionRoute
  '/emplois/$id': typeof EmploisIdRoute
  '/entreprises/$slug': typeof EntreprisesSlugRoute
  '/infos-pratiques/$slug': typeof InfosPratiquesSlugRoute
  '/actualites': typeof ActualitesIndexRoute
  '/admin': typeof AdminIndexRoute
  '/emplois': typeof EmploisIndexRoute
  '/entreprises': typeof EntreprisesIndexRoute
  '/infos-pratiques': typeof InfosPratiquesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/connexion': typeof ConnexionRoute
  '/espace-entreprise': typeof EspaceEntrepriseRoute
  '/espace-utilisateur': typeof EspaceUtilisateurRoute
  '/publier-actualite': typeof PublierActualiteRoute
  '/publier-offre': typeof PublierOffreRoute
  '/signaler': typeof SignalerRoute
  '/tableau-structure': typeof TableauStructureRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/admin/$section': typeof AdminSectionRoute
  '/emplois/$id': typeof EmploisIdRoute
  '/entreprises/$slug': typeof EntreprisesSlugRoute
  '/infos-pratiques/$slug': typeof InfosPratiquesSlugRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/emplois/': typeof EmploisIndexRoute
  '/entreprises/': typeof EntreprisesIndexRoute
  '/infos-pratiques/': typeof InfosPratiquesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assistant'
    | '/connexion'
    | '/espace-entreprise'
    | '/espace-utilisateur'
    | '/publier-actualite'
    | '/publier-offre'
    | '/signaler'
    | '/tableau-structure'
    | '/actualites/$slug'
    | '/admin/$section'
    | '/emplois/$id'
    | '/entreprises/$slug'
    | '/infos-pratiques/$slug'
    | '/actualites/'
    | '/admin/'
    | '/emplois/'
    | '/entreprises/'
    | '/infos-pratiques/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/connexion'
    | '/espace-entreprise'
    | '/espace-utilisateur'
    | '/publier-actualite'
    | '/publier-offre'
    | '/signaler'
    | '/tableau-structure'
    | '/actualites/$slug'
    | '/admin/$section'
    | '/emplois/$id'
    | '/entreprises/$slug'
    | '/infos-pratiques/$slug'
    | '/actualites'
    | '/admin'
    | '/emplois'
    | '/entreprises'
    | '/infos-pratiques'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assistant'
    | '/connexion'
    | '/espace-entreprise'
    | '/espace-utilisateur'
    | '/publier-actualite'
    | '/publier-offre'
    | '/signaler'
    | '/tableau-structure'
    | '/actualites/$slug'
    | '/admin/$section'
    | '/emplois/$id'
    | '/entreprises/$slug'
    | '/infos-pratiques/$slug'
    | '/actualites/'
    | '/admin/'
    | '/emplois/'
    | '/entreprises/'
    | '/infos-pratiques/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  ConnexionRoute: typeof ConnexionRoute
  EspaceEntrepriseRoute: typeof EspaceEntrepriseRoute
  EspaceUtilisateurRoute: typeof EspaceUtilisateurRoute
  PublierActualiteRoute: typeof PublierActualiteRoute
  PublierOffreRoute: typeof PublierOffreRoute
  SignalerRoute: typeof SignalerRoute
  TableauStructureRoute: typeof TableauStructureRoute
  ActualitesSlugRoute: typeof ActualitesSlugRoute
  EmploisIdRoute: typeof EmploisIdRoute
  EntreprisesSlugRoute: typeof EntreprisesSlugRoute
  InfosPratiquesSlugRoute: typeof InfosPratiquesSlugRoute
  ActualitesIndexRoute: typeof ActualitesIndexRoute
  EmploisIndexRoute: typeof EmploisIndexRoute
  EntreprisesIndexRoute: typeof EntreprisesIndexRoute
  InfosPratiquesIndexRoute: typeof InfosPratiquesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace-entreprise': {
      id: '/espace-entreprise'
      path: '/espace-entreprise'
      fullPath: '/espace-entreprise'
      preLoaderRoute: typeof EspaceEntrepriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace-utilisateur': {
      id: '/espace-utilisateur'
      path: '/espace-utilisateur'
      fullPath: '/espace-utilisateur'
      preLoaderRoute: typeof EspaceUtilisateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publier-actualite': {
      id: '/publier-actualite'
      path: '/publier-actualite'
      fullPath: '/publier-actualite'
      preLoaderRoute: typeof PublierActualiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publier-offre': {
      id: '/publier-offre'
      path: '/publier-offre'
      fullPath: '/publier-offre'
      preLoaderRoute: typeof PublierOffreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signaler': {
      id: '/signaler'
      path: '/signaler'
      fullPath: '/signaler'
      preLoaderRoute: typeof SignalerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableau-structure': {
      id: '/tableau-structure'
      path: '/tableau-structure'
      fullPath: '/tableau-structure'
      preLoaderRoute: typeof TableauStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/': {
      id: '/actualites/'
      path: '/actualites'
      fullPath: '/actualites/'
      preLoaderRoute: typeof ActualitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/$slug': {
      id: '/actualites/$slug'
      path: '/actualites/$slug'
      fullPath: '/actualites/$slug'
      preLoaderRoute: typeof ActualitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$section': {
      id: '/admin/$section'
      path: '/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AdminSectionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/emplois/': {
      id: '/emplois/'
      path: '/emplois'
      fullPath: '/emplois/'
      preLoaderRoute: typeof EmploisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emplois/$id': {
      id: '/emplois/$id'
      path: '/emplois/$id'
      fullPath: '/emplois/$id'
      preLoaderRoute: typeof EmploisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprises/': {
      id: '/entreprises/'
      path: '/entreprises'
      fullPath: '/entreprises/'
      preLoaderRoute: typeof EntreprisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprises/$slug': {
      id: '/entreprises/$slug'
      path: '/entreprises/$slug'
      fullPath: '/entreprises/$slug'
      preLoaderRoute: typeof EntreprisesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infos-pratiques/': {
      id: '/infos-pratiques/'
      path: '/infos-pratiques'
      fullPath: '/infos-pratiques/'
      preLoaderRoute: typeof InfosPratiquesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infos-pratiques/$slug': {
      id: '/infos-pratiques/$slug'
      path: '/infos-pratiques/$slug'
      fullPath: '/infos-pratiques/$slug'
      preLoaderRoute: typeof InfosPratiquesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminSectionRoute: typeof AdminSectionRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSectionRoute: AdminSectionRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AssistantRoute: AssistantRoute,
  ConnexionRoute: ConnexionRoute,
  EspaceEntrepriseRoute: EspaceEntrepriseRoute,
  EspaceUtilisateurRoute: EspaceUtilisateurRoute,
  PublierActualiteRoute: PublierActualiteRoute,
  PublierOffreRoute: PublierOffreRoute,
  SignalerRoute: SignalerRoute,
  TableauStructureRoute: TableauStructureRoute,
  ActualitesSlugRoute: ActualitesSlugRoute,
  EmploisIdRoute: EmploisIdRoute,
  EntreprisesSlugRoute: EntreprisesSlugRoute,
  InfosPratiquesSlugRoute: InfosPratiquesSlugRoute,
  ActualitesIndexRoute: ActualitesIndexRoute,
  EmploisIndexRoute: EmploisIndexRoute,
  EntreprisesIndexRoute: EntreprisesIndexRoute,
  InfosPratiquesIndexRoute: InfosPratiquesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
